[project]
name = "loadcell-hx711-mvc"
version = "0.2.0"
description = "Software for the Use-The-Force experiment using the Thorlabs setup -- MVC structure"
readme = "README.md"
authors = [
    { name = "DylanvanArneman", email = "51400178+DylanvanArneman@users.noreply.github.com" }
]
requires-python = ">=3.10"
dependencies = [
    "numpy>=2.2.4",
    "pyserial>=3.5",
    "pyvisa>=1.16.2",
    "pyvisa-py>=0.8.1",
]

[project.scripts]
loadcell-hx711-mvc = "loadcell_hx711_mvc:main"

[build-system]
requires = ["uv_build>=0.9.26,<0.10.0"]
build-backend = "uv_build"
